/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SignalRouteLazyImport = createFileRoute('/signal')()
const IndexRouteLazyImport = createFileRoute('/')()

// Create/Update Routes

const SignalRouteLazyRoute = SignalRouteLazyImport.update({
  path: '/signal',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signal/route.lazy').then((d) => d.Route))

const IndexRouteLazyRoute = IndexRouteLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index/route.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/signal': {
      id: '/signal'
      path: '/signal'
      fullPath: '/signal'
      preLoaderRoute: typeof SignalRouteLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRouteLazyRoute,
  SignalRouteLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/signal"
      ]
    },
    "/": {
      "filePath": "index/route.lazy.tsx"
    },
    "/signal": {
      "filePath": "signal/route.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
