name: Publish to JSR

on:
  pull_request:
    types:
      - closed
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish-jsr:
    name: Publish to JSR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'changeset-release/main'

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      - name: Build @kaiverse/* packages
        run: pnpm build:pkgs
        env:
          TURBO_TELEMETRY_DISABLED: 1

      - name: JSR versioning
        run: pnpm dlx tsx ./scripts/jsr-versioning.ts

      - name: Publish @kaiverse/signal to JSR
        run: pnpm dlx jsr publish --allow-dirty
        working-directory: ./packages/signal

      - name: Publish @kaiverse/signal-react to JSR
        run: pnpm dlx jsr publish --allow-dirty
        working-directory: ./packages/signal-react
